---
title: "data cleaning"
author: "Clint McKenna"
date: "March 6th, 2020"
output: html_document
---

## data prep
```{r, message = FALSE}
# load packages
library(readxl)
library(psych)
library(knitr)
library(tidyverse)

# custom functions
# dplyr select
select <- dplyr::select
# custom function to rename all columns to character
toChar <- function(df){
  df %>% mutate_all(as.character)
}
# mode 
getMode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

# oTree data
# search data directory for excel files for raw oTree data
datFiles <- dir(path = '../data/raw/oTree',
              pattern = '*.xlsx',
              recursive = TRUE,
              full.names = TRUE)

# read in all data
datRaw <- datFiles %>%
  map(read_excel) %>%
  map(toChar) %>%
  reduce(full_join)


# new dataframe, preserving raw data
dat <- datRaw

# create workerID var
dat <- dat %>%
  mutate(workerId = participant.label)



# get turkprime data to examine those who completed HIT
# search data directory for turkprime .csv files
TPFiles <- dir(path = '../data/raw/turkprime',
                      pattern = '*.csv',
                      recursive = TRUE,
                      full.names = TRUE)

# join csv, mutating survey file number
turkprime <- TPFiles %>%
  map(read_csv) %>% 
  imap(~ mutate(.x, survey = .y)) %>%
  reduce(full_join)

# replace survey number with D or R
turkprime <- turkprime %>%
  mutate(survey = TPFiles[turkprime$survey]) %>%
  select(workerId = AmazonIdentifier, survey)
turkprime$survey <- gsub('.*misinfo_', '', turkprime$survey)
turkprime$survey <- gsub('[ [].*', '', turkprime$survey)

# join with dat
dat <- left_join(dat, turkprime, by = 'workerId')


# remove clutter
rm(datRaw, datFiles, TPFiles, turkprime)

```


## rename and clean up vars
```{r}
# select vars we care about
dat <- dat %>%
  transmute(
    subject = 1:nrow(.),
    role = misinfoNet.1.player.p,
    condition = misinfoNet.1.player.condition,
    moralCondition = misinfoNet.1.player.moralCondition,
    n1 = misinfoNet.1.player.n1,
    n2 = misinfoNet.1.player.n2,
    n3 = misinfoNet.1.player.n3,
    n4 = misinfoNet.1.player.n4,
    r1_response = misinfoNet.1.player.response,
    r1_answer = misinfoNet.1.player.answer,
    r1_mLog = misinfoNet.1.player.mLog,
    r1_n1Rating = misinfoNet.1.player.n1Rating,
    r1_n2Rating = misinfoNet.1.player.n2Rating,
    r1_n3Rating = misinfoNet.1.player.n3Rating,
    r1_n4Rating = misinfoNet.1.player.n4Rating,
    r2_response = misinfoNet.2.player.response,
    r2_answer = misinfoNet.2.player.answer,
    r2_mLog = misinfoNet.2.player.mLog,
    r2_n1Rating = misinfoNet.2.player.n1Rating,
    r2_n2Rating = misinfoNet.2.player.n2Rating,
    r2_n3Rating = misinfoNet.2.player.n3Rating,
    r2_n4Rating = misinfoNet.2.player.n4Rating,
    r3_response = misinfoNet.3.player.response,
    r3_answer = misinfoNet.3.player.answer,
    r3_mLog = misinfoNet.3.player.mLog,
    r3_n1Rating = misinfoNet.3.player.n1Rating,
    r3_n2Rating = misinfoNet.3.player.n2Rating,
    r3_n3Rating = misinfoNet.3.player.n3Rating,
    r3_n4Rating = misinfoNet.3.player.n4Rating,
    r4_response = misinfoNet.4.player.response,
    r4_answer = misinfoNet.4.player.answer,
    r4_mLog = misinfoNet.4.player.mLog,
    r4_n1Rating = misinfoNet.4.player.n1Rating,
    r4_n2Rating = misinfoNet.4.player.n2Rating,
    r4_n3Rating = misinfoNet.4.player.n3Rating,
    r4_n4Rating = misinfoNet.4.player.n4Rating,
    strat = misinfoNet_outro.1.player.strat,
    stratExplain = misinfoNet_outro.1.player.stratExplain,
    berlin1 = misinfoNet_outro.1.player.berlin1,
    berlin2 = misinfoNet_outro.1.player.berlin2,
    berlin3 = misinfoNet_outro.1.player.berlin3,
    berlin4 = misinfoNet_outro.1.player.berlin4,
    gun = misinfoNet_outro.1.player.gun,
    age = misinfoNet_outro.1.player.age,
    gender = misinfoNet_outro.1.player.gender,
    genderOther = misinfoNet_outro.1.player.genderOther,
    ethnicity = misinfoNet_outro.1.player.ethnicity,
    ethnicityOther = misinfoNet_outro.1.player.ethnicityOther,
    eduYear = misinfoNet_outro.1.player.eduYear,
    politics = misinfoNet_outro.1.player.politics,
    party = misinfoNet_outro.1.player.party,
    feedback = misinfoNet_outro.1.player.studyFeedback,
    robot = misinfoNet_outro.1.player.robot,
    honesty = misinfoNet_outro.1.player.honesty,
    workerId = workerId,
    session = session.code,
    survey = survey)

```

## experimental conditions and scoring
```{r}
# reverse condition
dat <- dat %>%
  mutate(revCondition = case_when(
    condition == 'guns'  ~ 0,
    condition == 'gunsR' ~ 1,
    TRUE ~ NA_real_))

# self-reported strategy
# correct strategy (dichotomous)
dat <- dat %>%
  mutate(strat01 = case_when(
    strat == 'How the ratio 223:75 compared to the ratio 107:21' ~ 1,
    is.na(strat) ~ NA_real_,
    TRUE ~ 0))

# create combined condition var
dat <- dat %>%
  mutate(condition2 = paste(condition, moralCondition, sep = '_'))

# correct interpretation
# create new dataframe for scoring
rounds <- dat %>%
  select(subject, condition, moralCondition, condition2, survey,
         r1_answer, r2_answer, r3_answer, r4_answer,
         r1_response, r2_response, r3_response, r4_response,
         r1_mLog, r2_mLog, r3_mLog, r4_mLog) %>%
  mutate(r1 = paste(r1_answer, r1_response, r1_mLog, sep = '___'),
         r2 = paste(r2_answer, r2_response, r1_mLog, sep = '___'),
         r3 = paste(r3_answer, r3_response, r1_mLog, sep = '___'),
         r4 = paste(r4_answer, r4_response, r1_mLog, sep = '___')) %>%
  gather(round, value = tempString, c(r1, r2, r3, r4)) %>%
  separate(tempString, c('answer', 'response', 'mLog'), sep = '___') %>%
  select(- starts_with('r1_'),
         - starts_with('r2_'),
         - starts_with('r3_'),
         - starts_with('r4_'))
        
# score correct depending on condition
# 0 - reported an decrease in crime
# 1 - reported an increase in crime
rounds <- rounds %>%
  mutate(correct = case_when(
    answer == 0  & condition == 'guns'  ~ 1, 
    answer == 1  & condition == 'guns'  ~ 0, 
    answer == 1  & condition == 'gunsR'  ~ 1, 
    answer == 0  & condition == 'gunsR'  ~ 0, 
    TRUE ~ NA_real_))

# congeniality conditions
rounds <- rounds %>%
  mutate(congenialMisinfo = case_when(
    condition == 'guns' & survey == 'D' ~ 'uncongenial',
    condition == 'gunsR' & survey == 'D' ~ 'congenial',
    condition == 'gunsR' & survey == 'R' ~ 'uncongenial',
    condition == 'guns' & survey == 'R' ~ 'congenial',
    TRUE ~ NA_character_))

# and for main dataset
scores <- rounds %>% 
  select(subject, round, correct) %>%
  spread(key = 'round', value = 'correct') %>%
  rename(r1_correct = r1, r2_correct = r2, r3_correct = r3, r4_correct = r4)
dat <- left_join(dat, scores, by = 'subject')

# sub out round column text
rounds$round <- gsub('[A-z]', '', rounds$round) %>%
  as.numeric()

# remove clutter
rm(scores)
```

## berlin numeracy test
```{r}

# calculate scores for BNT
dat <- dat %>%
  mutate(
    berlin1 = case_when(
      berlin1 == '30 out of 50 throws' ~ 1,
      is.na(berlin1) ~ NA_real_,
      TRUE ~ 0),
    berlin2 = case_when(
      berlin2 == '25%' ~ 1, 
      is.na(berlin2) ~ NA_real_,
      TRUE ~ 0),
    berlin3 = case_when(
      berlin3 == '20 out of 70 throws' ~ 1, 
      is.na(berlin3) ~ NA_real_,
      TRUE ~ 0),
    berlin4 = case_when(
      berlin4 == '50%' ~ 1, 
      is.na(berlin4) ~ NA_real_,
      TRUE ~ 0)) %>%
  mutate(bnt = berlin1 + berlin2 + berlin3 + berlin4) %>%
  mutate(bnt = case_when(
    is.na(berlin1)|is.na(berlin2)|is.na(berlin3)|is.na(berlin4) ~ NA_real_, 
    TRUE ~ bnt))

# check alpha
dat %>%
  select(berlin1, berlin2, berlin3, berlin4) %>%
  psych::alpha(title = 'bnt')

```


## pew gun attitudes
```{r}
# column names for individual gun items
gunColNames <- c('rightFreedom', 'bigProb', 'moreStrict', 'everyoneOwn', 'placeOfflimits', 'mostLegal', 'moreCrime', 'fewerShootings')

# separate columns into individuals for each item
dat <- dat %>%
  mutate(gun = gsub('\\[|\\]|\'|[[:space:]]', '', .$gun)) %>%
  separate(gun, sep = ',', gunColNames) %>%
  mutate_at(gunColNames, funs(as.numeric(.)))

# reverse code items so higher numbers = more support for gun control
dat$rightFreedom <- 6 - dat$rightFreedom
dat$everyoneOwn <- 6 - dat$everyoneOwn
dat$mostLegal <- 6 - dat$mostLegal

# factor analysis with all items
gunFA.all <- fa(dat[, gunColNames], nfactors = 8, rotate = 'none')
gunFA.all

# scree plot
plot(gunFA.all$e.values, type = 'b')

# looks like only 1 factor...
# rerun FA with oblique rotation
gunFA <- fa(dat[, gunColNames], nfactors = 1, rotate = 'oblimin')
gunFA

# create table of factor loadings
tab.gunFA <- unclass(gunFA$loadings) %>%
  round(digits = 2) %>%
  ifelse(. > .3, ., '') %>%
  kable()
tab.gunFA

# diagram
fa.diagram(gunFA, digits = 2, main = 'Factor Analysis Gun Control Items')

# create index with all items
dat <- dat %>%
  mutate(gunAtt = rowMeans(.[, gunColNames], na.rm = TRUE))

# check cronbach's alpha
dat %>%
 select(gunColNames) %>%
 psych::alpha(title = 'gunAtt')

# remove clutter
rm(gunFA, gunFA.all, gunColNames, tab.gunFA)
```


## demographics and politics
```{r}
# age
dat <- dat %>%
  mutate(age = as.numeric(age))

# gender (female)
dat <- dat %>%
  mutate(female = case_when(
    gender == 'Female' ~ 1,
    gender == 'Male' ~ 0,
    TRUE ~ NA_real_))

# education
dat <- dat %>%
  mutate(education = case_when(
    eduYear == 'Some High School' ~ 0,
    eduYear == 'High School Graduate' ~ 1,
    eduYear == 'Some College' ~ 2,
    eduYear == '4-Year College Graduate (B.A. or B.S.)' ~ 3,
    eduYear == 'Graduate or Professional School (M.D., J.D., Ph.D.' ~ 4,
    eduYear == 'Don\'t know/Prefer not to respond' ~ NA_real_,
    TRUE ~ NA_real_))

# ethnicity
dat <- dat %>%
  mutate(white = case_when(
    grepl('white', ethnicity) ~ 1,
    TRUE ~ 0)) %>%
  mutate(black = case_when(
    grepl('black', ethnicity) ~ 1,
    TRUE ~ 0)) %>%
  mutate(asian = case_when(
    grepl('asian', ethnicity) ~ 1,
    TRUE ~ 0)) %>%
  mutate(nativeAm = case_when(
    grepl('nativeAm', ethnicity) ~ 1,
    TRUE ~ 0)) %>%
  mutate(latino = case_when(
    grepl('latino', ethnicity) ~ 1,
    TRUE ~ 0)) %>%
  mutate(otherEthnicity = case_when(
    grepl('other', ethnicity) ~ 1,
    TRUE ~ 0)) %>%
  mutate(preferNotEthnicity = case_when(
    grepl('preferNot', ethnicity) ~ 1,
    TRUE ~ 0)) %>%
  mutate(multiracial = case_when(
    white + black + latino + asian + nativeAm + otherEthnicity > 1 ~ 1,
    TRUE ~ 0)) %>%
  mutate(ethnicity = case_when(
    multiracial == 1 ~ 'multiracial',
    white == 1 & multiracial == 0 ~ 'white',
    black == 1 & multiracial == 0 ~ 'black',
    latino == 1 & multiracial == 0 ~ 'latino',
    asian == 1 & multiracial == 0 ~ 'asian',
    nativeAm == 1 & multiracial == 0 ~ 'nativeAm',
    TRUE ~ NA_character_))

# politics - 7 point scale, only interested in liberal-conservative, else coded NA
dat <- dat %>%
  mutate(conservatism = case_when(
    politics == 'Very Liberal' ~ 0,
    politics == 'Liberal' ~ 1,
    politics == 'Slightly Liberal' ~ 2,
    politics == 'Moderate/Middle-of-the-road' ~ 3,
    politics == 'Slightly Conservative' ~ 4,
    politics == 'Conservative' ~ 5,
    politics == 'Very Conservative' ~ 6,
    TRUE ~ NA_real_))

# party - only interested in republican/democrat, else coded NA
dat <- dat %>%
  mutate(republican = case_when(
    party == 'Republican' ~ 1,
    party == 'Democrat' ~ 0,
    TRUE ~ NA_real_))

```


## generate edgelist
```{r}

# select vars
edgelist <- dat %>%
  select(subject, session, condition, moralCondition, condition2, 
         sender = role, n1, n2, n3, n4)

# reshapre wide to long
edgelist <- edgelist %>%
  group_by(session) %>%
  gather(neighbor, value = receiver, c(n1, n2, n3, n4)) %>%
  select(sender, receiver, everything()) %>%
  ungroup()

```


## mouse logging var (new method)
```{r}
# select vars
mLog <- dat %>%
  select(subject, r1_mLog, r2_mLog, r3_mLog, r4_mLog)


# empty list
logList <- list()

# for loop
for (i in 1:as.numeric(nrow(mLog))) {
  
  # current subject
  currentSub <- mLog[i,]
  
  # split mLog string 
  splitLog <- str_split(currentSub$log, ';')
  
  # new dataframe with subject number and log
  newDat <- data.frame(
    subject = currentSub[1, 1],
    log = splitLog[[1]])
  
  # remove 'cell' and ',cell' from log string
  newDat$log <- gsub(',cell', '', newDat$log)
  newDat$log <- gsub('cell', '', newDat$log)
  
  # remove 'start:' and 'end:' from string
  newDat$log <- gsub('start:', '', newDat$log)
  newDat$log <- gsub('end:', '', newDat$log)

  # na omit
  newDat$log[newDat$log == ''] <- NA
  newDat <- na.omit(newDat)
  
  # split log columns: cell, start time, end time
  newDat <- newDat %>%
    separate(log, c('cell', 'start', 'end'), sep = ',')
  
  # save in list
  logList[[i]] <-  data.frame(newDat)
  
  # remove clutter in each loop
  rm(newDat, currentSub, splitLog)
  
}

# combine into long dataframe
mLogLong <- do.call('rbind', logList)

# new vars for long list
mLogLong <- mLogLong %>%
  mutate(start = as.numeric(start),
         end = as.numeric(end)) %>%
  mutate(hoverTime = end - start)

# rename mLog
mLog <- mLogLong

# remove clutter
rm(mLogLong, logList)


```


## clean up and export
```{r}
# select only vars of note
# dat <- dat %>%
#   select(subject, role, party, condition, 
#          n1, n2, n3, n4,
#          r1_score, r2_score, r3_score, r4_score,
#          impeachKnowledge, age, gender, feedback)

# export
write_csv(dat, '../data/data.csv')
write_csv(rounds, '../data/rounds.csv')
write_csv(edgelist, '../data/edgelist.csv')

# clear clutter
rm(dat, edgelist, rounds)

```


