---
title: "network"
author: "Clint McKenna"
date: "February 20th, 2020"
output: html_document
---

## data prep
```{r, message = FALSE}
# load packages
library(igraph)
library(ggraph)
library(patchwork)
library(tidyverse)

# custom functions
# dplyr select
select <- dplyr::select

# read in data seperately
dat <- read_csv('../data/data.csv')
rounds <- read_csv('../data/rounds.csv')
edgelist <- read_csv('../data/edgelist.csv')

```


## prepare network objects
```{r}
# for the next steps, we need to put sender/receiver first
edgelist <- edgelist %>%
  select(sender, receiver, subject, condition2, session)

# for simplicity, remove 'Participant ' from edgelist text
edgelist$sender <- gsub('Participant ', '', edgelist$sender)
edgelist$receiver <- gsub('Participant ', '', edgelist$receiver)


# retrieve vertex scores from initial dataset
vertexScores <- dat %>%
  select(role, r1_correct, r2_correct, r3_correct, r4_correct, subject, session, condition2)

# removing text from role in vertexScores
vertexScores$role <- gsub('Participant ', '', vertexScores$role)

# set Participant D's data
d <- data.frame(
  sender = rep('D', 4),
  receiver = c('B', 'C', 'E', 'F'),
  subject = 0)
dV = data.frame(
  role = 'D',
  r1_correct = 0,
  r1_correct = 0,
  r1_correct = 0,
  r1_correct = 0,
  subject = 0,
  session = NA,
  condition2 = NA)

# get unique session ids
sessions <- edgelist$session %>% unique()


# now, make 8 network objects, one for each condition

# function to iterate through session vector
getNet <- function(x) {
  
  # get edgelist and vertex attributes for session
  currentEdge <- edgelist %>% 
    filter(session == x) %>%
    select(sender, receiver, subject)
  
  currentVertex <- vertexScores %>% 
    filter(session == x)
  
  # append data with misinfo node
  currentEdge <- bind_rows(currentEdge, d)
  currentVertex <- bind_rows(currentVertex, dV)
  
  # sort edgelist by sender
  currentEdge <- currentEdge[order(currentEdge$sender),]
  currentVertex <- currentVertex[order(currentVertex$role),]
  
  # create network object. non-directed
  currentNet <- graph_from_data_frame(
    currentEdge,
    directed = FALSE,
    vertices = currentVertex
  )
  
  # output net object
  return(currentNet)
  
}

# get list of all network objects
netList <- sessions %>%
  map(~ getNet(.))


```



## multiple plots
```{r}





plotNets <- function(x) {
  
  # define current network object
  currentNet <- x
  
  
  ggraph(nets, layout = 'circle') +
    geom_edge_link() +
    geom_node_text(aes(label = names(V(currentNet)))) +
    geom_node_point(aes(color = as.factor(V(currentNet)$r1_correct)), size = 10, alpha = .75) +
    scale_color_manual(values = c('red', 'light blue')) +
    labs(
      title = 'Baseline',
      color = 'Misinformation Endorsed') +
    theme_graph()
  
}











# define number of loops and plot list
plotList <- list()
nNet <- as.numeric(length(netList))

# for loop to iterate through netList
for (i in 1:nNet) {
  
  # define current network object
  currentNet <- netList[[i]]
  
  # plot
  plotList[[i]] <- ggraph(currentNet, layout = 'circle') +
    geom_edge_link() +
    geom_node_text(aes(label = names(V(currentNet)))) +
    geom_node_point(aes(color = as.factor(V(currentNet)$r1_correct)), size = 10, alpha = .75) +
    scale_color_manual(values = c('red', 'light blue')) +
    labs(
      title = 'Baseline',
      color = 'Misinformation Endorsed') +
    theme_graph()

}  

# Build multiplot panel (two columns)
# 
# pngname<-paste(output_path,"plot-name",".png",sep="")
# png(pngname,width = 1000, height = 1000)
# do.call(grid.arrange, c(ggcluster,list(ncol=2)))
# dev.off()
```




















## plot with ggraph package
```{r}

currentNet <- netList[[2]]

ggraph(currentNet, layout = 'circle') +
  geom_edge_link() +
  geom_node_text(aes(label = names(V(currentNet)))) +
  geom_node_point(aes(color = as.factor(V(currentNet)$r1_correct)), size = 10, alpha = .75) +
  scale_color_manual(values = c('red', 'light blue')) +
  labs(
    title = 'Baseline',
    color = 'Misinformation Endorsed') +
  theme_graph()


```



## patchwork each timepoint together
```{r}

net1 <- netList[[7]]


# baseline
pBaseline <- ggraph(net1, layout = 'circle') +
  geom_edge_link() +
  geom_node_point(color = 'white', size = 10) +
  geom_node_point(aes(color = as.factor(V(net1)$r1_correct)), size = 8, alpha = .75) +
  scale_color_manual(values = c('red', '#3b5998'), na.value = 'light grey') +
  labs(
    title = V(net1)$session,
    subtitle = V(net1)$condition2
    ) +
  theme_graph() +
  theme(legend.position = 'none') + 
  coord_cartesian(xlim=c(-1.4,1.4), ylim=c(-1.4,1.4))

# update - round 1 (r2)
p1 <- ggraph(net1, layout = 'circle') +
  geom_edge_link() +
  geom_node_point(color = 'white', size = 10) +
  geom_node_point(aes(color = as.factor(V(net1)$r2_correct)), size = 8, alpha = .75) +
  scale_color_manual(values = c('red', '#3b5998'), na.value = 'light grey') +
  labs(
    title = 'Round 1') +
  theme_graph() +
  theme(legend.position = 'none') + 
  coord_cartesian(xlim=c(-1.4,1.4), ylim=c(-1.4,1.4))

# update - round 2 (r3)
p2 <- ggraph(net1, layout = 'circle') +
  geom_edge_link() +
  geom_node_point(color = 'white', size = 10) +
  geom_node_point(aes(color = as.factor(V(net1)$r3_correct)), size = 8, alpha = .75) +
  scale_color_manual(values = c('red', '#3b5998'), na.value = 'light grey') +
  labs(
    title = 'Round 2') +
  theme_graph() +
  theme(legend.position = 'none') + 
  coord_cartesian(xlim=c(-1.4,1.4), ylim=c(-1.4,1.4))

# update - round 3 (r4)
p3 <- ggraph(net1, layout = 'circle') +
  geom_edge_link() +
  geom_node_point(color = 'white', size = 10) +
  geom_node_point(aes(color = as.factor(V(net1)$r4_correct)), size = 8, alpha = .75) +
  scale_color_manual(values = c('red', '#3b5998'), na.value = 'light grey') +
  labs(
    title = 'Round 3',
    color = 'Misinformation Endorsed',
    caption = 'Grey nodes indicate NA values') +
  theme_graph() + 
  theme(legend.position = 'none') + 
  coord_cartesian(xlim=c(-1.4,1.4), ylim=c(-1.4,1.4))


# output both plots
# pBaseline + p1 + p2 + p3 


# can also save to file in same way as before (run these lines altogether)
png('../figures/ggnet.png', units = 'in', width = 20, height = 5, res = 750)
(pBaseline | p1 | p2 | p3)
dev.off()

```






